name             'distributed-grep'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures distributed-grep'
long_description 'Installs/Configures distributed-grep'
version          '0.1.0'
